name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # roda diariamente
  workflow_dispatch:     # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: regibabr
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
